[Interface]
Address = 10.10.10.1/24
ListenPort = 51820
PrivateKey = oEuqrerkAS9gF2v+FtTg/CRNJd3u69eJIIj0eGY/B3k=

PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp = iptables -A FORWARD -o wg0 -j ACCEPT
PostUp = iptables -t nat -A PREROUTING -i eth0 -p udp -d 104.248.87.62 --dport 88 -j DNAT --to-destination 192.168.1.43:88
PostUp = iptables -t nat -A PREROUTING -i eth0 -p udp -d 104.248.87.62 --dport 3074 -j DNAT --to-destination 192.168.1.43:3074
PostUp = iptables -t nat -A PREROUTING -i eth0 -p udp -d 104.248.87.62 --dport 53 -j DNAT --to-destination 192.168.1.43:53
PostUp = iptables -t nat -A PREROUTING -i eth0 -p udp -d 104.248.87.62 --dport 500 -j DNAT --to-destination 192.168.1.43:500
PostUp = iptables -t nat -A PREROUTING -i eth0 -p udp -d 104.248.87.62 --dport 3544 -j DNAT --to-destination 192.168.1.43:3544
PostUp = iptables -t nat -A PREROUTING -i eth0 -p udp -d 104.248.87.62 --dport 4500 -j DNAT --to-destination 192.168.1.43:4500
PostUp = iptables -t nat -A PREROUTING -i eth0 -p tcp -d 104.248.87.62 --dport 3074 -j DNAT --to-destination 192.168.1.43:3074
PostUp = iptables -t nat -A PREROUTING -i eth0 -p tcp -d 104.248.87.62 --dport 53 -j DNAT --to-destination 192.168.1.43:53
PostUp = iptables -t nat -A PREROUTING -i eth0 -p tcp -d 104.248.87.62 --dport 80 -j DNAT --to-destination 192.168.1.43:80
PostUp = iptables -A FORWARD -i eth0 -o wg0 -p udp -d 192.168.1.43 -m multiport --dports 88,3074,53,500,3544,4500 -j ACCEPT
PostUp = iptables -A FORWARD -i eth0 -o wg0 -p tcp -d 192.168.1.43 -m multiport --dports 3074,53,80 -j ACCEPT

PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -o wg0 -j ACCEPT
PostDown = iptables -t nat -D PREROUTING -i eth0 -p udp -d 104.248.87.62 --dport 88 -j DNAT --to-destination 192.168.1.43:88
PostDown = iptables -t nat -D PREROUTING -i eth0 -p udp -d 104.248.87.62 --dport 3074 -j DNAT --to-destination 192.168.1.43:3074
PostDown = iptables -t nat -D PREROUTING -i eth0 -p udp -d 104.248.87.62 --dport 53 -j DNAT --to-destination 192.168.1.43:53
PostDown = iptables -t nat -D PREROUTING -i eth0 -p udp -d 104.248.87.62 --dport 500 -j DNAT --to-destination 192.168.1.43:500
PostDown = iptables -t nat -D PREROUTING -i eth0 -p udp -d 104.248.87.62 --dport 3544 -j DNAT --to-destination 192.168.1.43:3544
PostDown = iptables -t nat -D PREROUTING -i eth0 -p udp -d 104.248.87.62 --dport 4500 -j DNAT --to-destination 192.168.1.43:4500
PostDown = iptables -t nat -D PREROUTING -i eth0 -p tcp -d 104.248.87.62 --dport 3074 -j DNAT --to-destination 192.168.1.43:3074
PostDown = iptables -t nat -D PREROUTING -i eth0 -p tcp -d 104.248.87.62 --dport 53 -j DNAT --to-destination 192.168.1.43:53
PostDown = iptables -t nat -D PREROUTING -i eth0 -p tcp -d 104.248.87.62 --dport 80 -j DNAT --to-destination 192.168.1.43:80
PostDown = iptables -D FORWARD -i eth0 -o wg0 -p udp -d 192.168.1.43 -m multiport --dports 88,3074,53,500,3544,4500 -j ACCEPT
PostDown = iptables -D FORWARD -i eth0 -o wg0 -p tcp -d 192.168.1.43 -m multiport --dports 3074,53,80 -j ACCEPT

[Peer]
PublicKey = g9JPUCGRX0fqsTveem8mvEsH57VXOuRsa1Cp3Fwq+D0=
AllowedIPs = 192.168.1.0/24, 10.10.10.2/32
PersistentKeepalive = 25
