[Interface]
Address = 10.10.10.1/24
ListenPort = 51820
PrivateKey = oEuqrerkAS9gF2v+FtTg/CRNJd3u69eJIIj0eGY/B3k=

# NAT
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

# Stateful
PostUp = iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Allow WG traffic
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT

# DNAT (UDP)
PostUp = iptables -t nat -A PREROUTING -i eth0 -p udp --dport 88 -j DNAT --to-destination 192.168.1.43:88
PostUp = iptables -t nat -A PREROUTING -i eth0 -p udp --dport 3074 -j DNAT --to-destination 192.168.1.43:3074
PostUp = iptables -t nat -A PREROUTING -i eth0 -p udp --dport 53 -j DNAT --to-destination 192.168.1.43:53
PostUp = iptables -t nat -A PREROUTING -i eth0 -p udp --dport 500 -j DNAT --to-destination 192.168.1.43:500
PostUp = iptables -t nat -A PREROUTING -i eth0 -p udp --dport 3544 -j DNAT --to-destination 192.168.1.43:3544
PostUp = iptables -t nat -A PREROUTING -i eth0 -p udp --dport 4500 -j DNAT --to-destination 192.168.1.43:4500

# DNAT (TCP)
PostUp = iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 3074 -j DNAT --to-destination 192.168.1.43:3074
PostUp = iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 53 -j DNAT --to-destination 192.168.1.43:53
PostUp = iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to-destination 192.168.1.43:80

# NAT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# Stateful rule
PostDown = iptables -D FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# WG forwarding
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT

# DNAT (UDP)
PostDown = iptables -t nat -D PREROUTING -i eth0 -p udp --dport 88 -j DNAT --to-destination 192.168.1.43:88
PostDown = iptables -t nat -D PREROUTING -i eth0 -p udp --dport 3074 -j DNAT --to-destination 192.168.1.43:3074
PostDown = iptables -t nat -D PREROUTING -i eth0 -p udp --dport 53 -j DNAT --to-destination 192.168.1.43:53
PostDown = iptables -t nat -D PREROUTING -i eth0 -p udp --dport 500 -j DNAT --to-destination 192.168.1.43:500
PostDown = iptables -t nat -D PREROUTING -i eth0 -p udp --dport 3544 -j DNAT --to-destination 192.168.1.43:3544
PostDown = iptables -t nat -D PREROUTING -i eth0 -p udp --dport 4500 -j DNAT --to-destination 192.168.1.43:4500

# DNAT (TCP)
PostDown = iptables -t nat -D PREROUTING -i eth0 -p tcp --dport 3074 -j DNAT --to-destination 192.168.1.43:3074
PostDown = iptables -t nat -D PREROUTING -i eth0 -p tcp --dport 53 -j DNAT --to-destination 192.168.1.43:53
PostDown = iptables -t nat -D PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to-destination 192.168.1.43:80

[Peer]
PublicKey = g9JPUCGRX0fqsTveem8mvEsH57VXOuRsa1Cp3Fwq+D0=
AllowedIPs = 192.168.1.0/24, 10.10.10.2/32
PersistentKeepalive = 25
